const playlistData = [
  {
    id: 1,
    playlistName: 'Ambient Lounge I',
    genre: [],
    description: '',
    totalTime: '',
    photo: '',
    musics: [
      {
        piste: 1,
        artist: 'Moby',
        title: 'Porcelain',
        time: '4.01',
      },
      {
        piste: 2,
        artist: 'Tycho',
        title: 'Red bridge',
        time: '4.01',
      },
    ],
  },
  {
    id: 2,
    playlistName: 'Ambient Lounge II',
    genre: [],
    description: '',
    totalTime: '',
    photo: '',
    musics: [
      {
        piste: 1,
        artist: 'Bonobo',
        title: 'Dinosaurs',
        time: '3.57',
      },
      {
        piste: 2,
        artist: 'Oleg byonic',
        title: 'The sting',
        time: '5.45',
      },
    ],
  },
  {
    id: 3,
    playlistName: 'Best of Boards Of Canada',
    genre: [],
    description: '',
    totalTime: '',
    photo: '',
    musics: [
      {
        piste: 1,
        artist: 'Boards of Canada',
        title: 'Music is Math',
        time: '7.30',
      },
      {
        piste: 2,
        artist: 'Boards of Canada',
        title: 'An eagle in your mind',
        time: '7.30',
      },
      {
        piste: 3,
        artist: 'Boards of Canada',
        title: 'Peacock tail',
        time: '7.30',
      },
    ],
  },
  {
    id: 4,
    playlistName: 'Good Night',
    genre: [],
    description: '',
    totalTime: '',
    photo: '',
    musics: [
      {
        artist: '',
        title: '',
        time: '',
      },
    ],
  },
  {
    id: 5,
    playlistName: 'Best of Moby',
    genre: [],
    description: '',
    totalTime: '',
    photo: '',
    musics: [
      {
        piste: 1,
        artist: 'Moby',
        title: 'Porcelain',
        time: '4.01',
      },
      {
        piste: 2,
        artist: 'Moby',
        title: 'Mistake',
        time: '4.01',
      },
      {
        piste: 3,
        artist: 'Moby',
        title: 'The last day',
        time: '4.01',
      },
    ],
  },
  {
    id: 6,
    playlistName: 'IDM',
    genre: [],
    description: '',
    totalTime: '',
    photo: '',
    musics: [
      {
        piste: 1,
        artist: 'Saeonin',
        title: 'Glacier',
        time: '4.01',
      },
      {
        piste: 2,
        artist: 'Saeonin',
        title: 'Glacier',
        time: '4.01',
      },
    ],
  },
  {
    id: 7,
    playlistName: 'Best of Aphex Twin',
    genre: [],
    description: '',
    totalTime: '',
    photo: '',
    musics: [
      {
        piste: 1,
        artist: 'Aphex twin',
        title: 'Heliosphan',
        time: '7.30',
      },
      {
        piste: 2,
        artist: 'Aphex twin',
        title: 'Rhubarb',
        time: '7.30',
      },
      {
        piste: 3,
        artist: 'Aphex twin',
        title: 'Make a baby',
        time: '7.30',
      },
      {
        piste: 4,
        artist: 'Aphex twin',
        title: 'Didgeridoo',
        time: '7.30',
      },
    ],
  },
  {
    id: 8,
    playlistName: 'Soundtrack',
    genre: [],
    description: '',
    totalTime: '',
    photo: '',
    musics: [
      {
        artist: '',
        title: '',
        time: '',
      },
    ],
  },
  {
    id: 9,
    playlistName: 'Ambient Chillout',
    genre: [],
    description: '',
    totalTime: '',
    photo: '',
    musics: [
      {
        artist: '',
        title: '',
        time: '',
      },
    ],
  },
  {
    id: 10,
    playlistName: 'Lounge Cafe',
    genre: [],
    description: '',
    totalTime: '',
    photo: '',
    musics: [
      {
        artist: '',
        title: '',
        time: '',
      },
    ],
  },
  {
    id: 11,
    playlistName: 'Best of Eitan Reiter',
    genre: ['electronic', 'house'],
    description: '',
    totalTime: '',
    photo: '',
    musics: [
      {
        piste: 1,
        artist: 'Eitan Reiter',
        title: 'Happy fat kid',
        time: '7.30',
      },
      {
        piste: 2,
        artist: 'Eitan Reiter',
        title: 'Pyramid',
        time: '7.30',
      },
      {
        piste: 3,
        artist: 'Eitan Reiter',
        title: 'Choices',
        time: '7.30',
      },
      {
        piste: 4,
        artist: 'Eitan Reiter',
        title: 'Stardust (Pefect Stranger remix)',
        time: '7.30',
      },
      {
        piste: 5,
        artist: 'Eitan Reiter',
        title: 'The 1st (X dream remix)',
        time: '7.30',
      },
      {
        piste: 6,
        artist: 'Eitan Reiter',
        title: 'Ups and downs',
        time: '7.30',
      },
    ],
  },
  {
    id: 12,
    playlistName: 'Relax',
    genre: [],
    description: '',
    totalTime: '',
    photo: '',
    musics: [
      {
        artist: '',
        title: '',
        time: '',
      },
    ],
  },
  {
    id: 13,
    playlistName: 'Best of Solar Fields',
    genre: ['electronic', 'ambient', 'psybient', 'progressive trance'],
    description: '',
    totalTime: '',
    photo: 'https://f4.bcbits.com/img/0003471719_21.jpg',
    musics: [
      {
        piste: 1,
        artist: 'Solar Fields',
        title: 'Sol',
        time: '7.30',
      },
      {
        piste: 2,
        artist: 'Solar Fields',
        title: 'Times are good (sometimes remix)',
        time: '6.45',
      },
      {
        piste: 3,
        artist: 'Solar Fields',
        title: 'Sombrero',
        time: '7.30',
      },
      {
        piste: 4,
        artist: 'Solar Fields',
        title: 'Insum',
        time: '7.30',
      },
      {
        piste: 5,
        artist: 'Solar Fields',
        title: 'The stones are not too busy',
        time: '10.29',
      },
      {
        piste: 6,
        artist: 'Solar Fields',
        title: 'Kick back',
        time: '7.30',
      },
      {
        piste: 7,
        artist: 'Solar Fields',
        title: 'Swoosh',
        time: '7.30',
      },
      {
        piste: 8,
        artist: 'Solar Fields',
        title: 'Video 2007',
        time: '7.30',
      },
      {
        piste: 9,
        artist: 'Solar Fields',
        title: 'We are the dream',
        time: '7.30',
      },
      {
        piste: 10,
        artist: 'Solar Fields',
        title: 'Confusion Illusion remix',
        time: '7.30',
      },
      {
        piste: 11,
        artist: 'Solar Fields',
        title: 'Cocoon moon',
        time: '7.30',
      },
    ],
  },
  {
    id: 14,
    playlistName: 'Best of Ott',
    genre: [],
    description: '',
    totalTime: '',
    photo: '',
    musics: [
      {
        artist: '',
        title: '',
        time: '',
      },
    ],
  },
  {
    id: 15,
    playlistName: 'Best of Rone',
    genre: [],
    description: '',
    totalTime: '',
    photo: '',
    musics: [
      {
        artist: '',
        title: '',
        time: '',
      },
    ],
  },
  {
    id: 16,
    playlistName: 'Best of Koan',
    genre: [],
    description: '',
    totalTime: '',
    photo: '',
    musics: [
      {
        artist: '',
        title: '',
        time: '',
      },
    ],
  },
  {
    id: 17,
    playlistName: 'Best of Eric Hilton',
    genre: [],
    description: '',
    totalTime: '',
    photo: '',
    musics: [
      {
        artist: '',
        title: '',
        time: '',
      },
    ],
  },
];
