const playlistData = [
  {
    id: 1,
    playlistName: 'Ambient Lounge I',
    genre: ['ambient', 'lounge', 'chillout'],
    description: '',
    totalTime: '',
    photo: require('./asset/lounge-1-img.png'),
    youtube: 'https://www.youtube.com/watch?v=42wQOP1vAFc&list=PLGcMNmVTewK_a0OuuxYEUA9-wmU-rgioR',
    musics: [
      {
        track: 1,
        artist: 'Five Seasons',
        title: 'Kiss The Sky',
        time: 4.48,
        link: 'https://www.youtube.com/watch?v=42wQOP1vAFc',
      },
      {
        track: 2,
        artist: 'Jens Buchert',
        title: 'Ground Vibrations',
        time: 4.57,
        link: 'https://www.youtube.com/watch?v=8bwAs-IqgDY',
      },
      {
        track: 3,
        artist: 'Boards Of Canada',
        title: 'Macquarie Ridge',
        time: 4.57,
        link: 'https://www.youtube.com/watch?v=M8rCeggIZMY',
      },
      {
        track: 4,
        artist: 'Sweet Tooth',
        title: 'Walk With Me (Hiatus Remix)',
        time: 6.33,
        link: 'https://www.youtube.com/watch?v=7C6jS6Dncbk',
      },
      {
        track: 5,
        artist: 'MARION',
        title: 'Future Beginning',
        time: 3.55,
        link: 'https://www.youtube.com/watch?v=gg6uK63inxI',
      },
      {
        track: 6,
        artist: 'Kevin Paczesny',
        title: 'Awakening',
        time: 7.44,
        link: 'https://www.youtube.com/watch?v=J9lcwXLwkGw',
      },
      {
        track: 7,
        artist: 'Oleg Byonic',
        title: 'Unforgettable Sunset (Forgotten)',
        time: 9.19,
        link: 'https://www.youtube.com/watch?v=DgTfuBLm2dU',
      },
      {
        track: 8,
        artist: 'Parra For Cuva',
        title: 'Cloudline',
        time: 4.57,
        link: 'https://www.youtube.com/watch?v=iET-Pexriwk',
      },
      {
        track: 9,
        artist: 'Tycho',
        title: 'Red Bridge',
        time: 6.09,
        link: 'https://www.youtube.com/watch?v=VoE0gItF-08',
      },
      {
        track: 10,
        artist: 'Pensees',
        title: 'Lunamoth',
        time: 5.26,
        link: 'https://www.youtube.com/watch?v=RIz6EoqPBrs',
      },
      {
        track: 11,
        artist: 'Nox Vahn feat. Mimi Page',
        title: 'Dream Of Love (Anjunadeep 11 Mix)',
        time: 6.05,
        link: 'https://www.youtube.com/watch?v=iJtQKX8aYcY',
      },
    ],
  },
  {
    id: 2,
    playlistName: 'Ambient Lounge II',
    genre: ['ambient', 'lounge', 'chillout'],
    description: 'Just lean back and enjoy relaxed beats - II',
    totalTime: '',
    photo: require('./asset/lounge-2-img.png'),
    youtube: 'https://www.youtube.com/watch?v=ADjh-VPJtFc&list=PLGcMNmVTewK9vUqoe4fTMjI9xyXPzeGlK',
    musics: [
      {
        track: 1,
        artist: 'Bonobo',
        title: 'Dinosaurs',
        time: 3.56,
        link: 'https://www.youtube.com/watch?v=ADjh-VPJtFc',
      },
      {
        track: 2,
        artist: 'Oleg Byonic',
        title: 'The Sting (Summer Mix)',
        time: 5.46,
        link: 'https://www.youtube.com/watch?v=63jfHInGz6g',
      },
      {
        track: 3,
        artist: 'Boards Of Canada',
        title: 'Tears From The Compound Eye - Orland Beltran Edit',
        time: 4.03,
        link: 'https://www.youtube.com/watch?v=Ulx1fOBYp2s',
      },
      {
        track: 4,
        artist: 'All India Radio',
        title: 'One Twenty Four AM',
        time: 3.04,
        link: 'https://www.youtube.com/watch?v=9rpVuvo1lNM',
      },
      {
        track: 5,
        artist: 'Lemongrass',
        title: 'Bonne Nuit',
        time: 4.10,
        link: 'https://www.youtube.com/watch?v=QEZ6_3pPhzw',
      },
      {
        track: 6,
        artist: 'LeBuc',
        title: 'India',
        time: 5.11,
        link: 'https://www.youtube.com/watch?v=bukhjJezGJA',
      },
      {
        track: 7,
        artist: 'Chris Coco',
        title: 'Heavy Mellow (Jon Hopkins Remix)',
        time: 7.07,
        link: 'https://www.youtube.com/watch?v=9SjxfOAEGeY',
      },
      {
        track: 8,
        artist: 'Yppah',
        title: 'Soft Reset',
        time: 6.16,
        link: 'https://www.youtube.com/watch?v=t6t3eMVQTQc',
      },
      {
        track: 9,
        artist: 'Sobrenadar',
        title: 'Unn',
        time: 3.43,
        link: 'https://www.youtube.com/watch?v=__NzPrHwamE',
      },
      {
        track: 10,
        artist: 'Melorman',
        title: 'Love In The 90s',
        time: 3.28,
        link: 'https://www.youtube.com/watch?v=WyILnAfdB9s',
      },
      {
        track: 11,
        artist: 'Jens Buchert',
        title: 'Dawnrider',
        time: 5.49,
        link: 'https://www.youtube.com/watch?v=UUoYsEFV_No',
      },
    ],
  },
  {
    id: 3,
    playlistName: 'Best Of Boards Of Canada',
    genre: ['IDM', 'downtempo', 'ambient', 'psychedelica', 'electro'],
    description: 'Scottish electronic music duo consisting of brothers Michael Sandison and Marcus Eoin - influenced by psychedelic music and electronic music',
    totalTime: '',
    photo: require('./asset/boards-of-canada-img.png'),
    youtube: 'https://www.youtube.com/watch?v=lhPWJHrwgR4&list=PLGcMNmVTewK8m4EhNoFSxRkOrjdUYicI4',
    musics: [
      {
        track: 1,
        artist: 'Boards Of Canada',
        title: 'Music Is Math',
        time: 5.22,
        link: 'https://www.youtube.com/watch?v=lhPWJHrwgR4',
      },
      {
        track: 2,
        artist: 'Boards Of Canada',
        title: 'An Eagle In Your Mind',
        time: 6.26,
        link: 'https://www.youtube.com/watch?v=VCcU-vg-woY',
      },
      {
        track: 3,
        artist: 'Boards Of Canada',
        title: 'Everything You Do Is A Balloon',
        time: 7.0,
        link: 'https://www.youtube.com/watch?v=dQEmaj9C6ko',
      },
      {
        track: 4,
        artist: 'Boards Of Canada',
        title: 'Roygbiv',
        time: 2.32,
        link: 'https://www.youtube.com/watch?v=0nnqGDZnWhU',
      },
      {
        track: 5,
        artist: 'Boards Of Canada',
        title: 'Aquarius',
        time: 5.59,
        link: 'https://www.youtube.com/watch?v=rRcr5hYCxh0',
      },
      {
        track: 6,
        artist: 'Boards Of Canada',
        title: 'Happy Cycling',
        time: 7.52,
        link: 'https://www.youtube.com/watch?v=DAM7OeFpgoE',
      },
      {
        track: 7,
        artist: 'Boards Of Canada',
        title: 'Buckie High',
        time: 5.19,
        link: 'https://www.youtube.com/watch?v=l09cDh0k9kI',
      },
      {
        track: 8,
        artist: 'Boards Of Canada',
        title: 'Left Side Drive',
        time: 5.21,
        link: 'https://www.youtube.com/watch?v=nEdMHsQI2eY',
      },
      {
        track: 9,
        artist: 'Boards Of Canada',
        title: 'Oscar See Through Red Eye',
        time: 5.09,
        link: 'https://www.youtube.com/watch?v=Gwx-sl-4JXs',
      },
      {
        track: 10,
        artist: 'Boards Of Canada',
        title: 'Julie And Candy',
        time: 5.31,
        link: 'https://www.youtube.com/watch?v=4CfdWJ6BjF0',
      },
      {
        track: 11,
        artist: 'Boards Of Canada',
        title: 'Oirectine',
        time: 5.27,
        link: 'https://www.youtube.com/watch?v=INzGy3eqf7A',
      },
      {
        track: 12,
        artist: 'Boards Of Canada',
        title: 'In A Beautiful Place Out In The Country',
        time: 5.30,
        link: 'https://www.youtube.com/watch?v=zVWcptE6UAI',
      },
    ],
  },
  {
    id: 4,
    playlistName: 'Good Night',
    genre: ['ambient'],
    description: 'Time to sleep. Empty your mind, bring attention to the present, and introduce calmness and peace',
    totalTime: '',
    photo: require('./asset/good-night-img.png'),
    youtube: '',
    musics: [
      {
        track: 1,
        artist: 'Moby',
        title: 'The Lonely Night',
        time: 4.52,
        link: 'https://www.youtube.com/watch?v=4SO0qSfxqyk',
      },
      {
        track: 2,
        artist: 'Boards Of Canada',
        title: 'Peacock Tail',
        time: 5.25,
        link: 'https://www.youtube.com/watch?v=AExw3WLtXng',
      },
      {
        track: 3,
        artist: 'Aphex Twin',
        title: 'Stone In Focus',
        time: 10.12,
        link: 'https://www.youtube.com/watch?v=q86g1aop6a8',
      },
      {
        track: 4,
        artist: 'Moby',
        title: 'A Seated Night (Ambient Mix)',
        time: 3.59,
        link: 'https://www.youtube.com/watch?v=pwTZMevJFOg',
      },
      {
        track: 5,
        artist: 'Jon Hopkins',
        title: 'Fairytale',
        time: 4.53,
        link: 'https://www.youtube.com/watch?v=rlNL37nH8oU',
      },
      {
        track: 6,
        artist: 'Christ',
        title: 'Stained Century',
        time: 5.45,
        link: 'https://www.youtube.com/watch?v=DaJLn12eTQk',
      },
      {
        track: 7,
        artist: 'Autechre',
        title: 'VLetrmx21',
        time: 8.28,
        link: 'https://www.youtube.com/watch?v=nVDMRGKCxh4',
      },
      {
        track: 8,
        artist: 'Man Of No Ego',
        title: 'Harmony Of The Universe',
        time: 8.46,
        link: 'https://www.youtube.com/watch?v=x7qyHX0xzHY',
      },
      {
        track: 9,
        artist: 'Lauge',
        title: 'Himalaya',
        time: 7.01,
        link: 'https://www.youtube.com/watch?v=vPPsPRm7T5o',
      },
      {
        track: 10,
        artist: 'Carbon Based Lifeforms',
        title: 'RCA (-)',
        time: 5.26,
        link: 'https://www.youtube.com/watch?v=p3hJigedaf4',
      },
      {
        track: 11,
        artist: 'Headphone Activist',
        title: 'Endocannabinoid',
        time: 3.20,
        link: 'https://www.youtube.com/watch?v=kHy5D8GFe_Y',
      },
      {
        track: 12,
        artist: 'Leven Canyon',
        title: 'The Good Night Chorale',
        time: 7.22,
        link: 'https://soundcloud.com/user-845854441/the-good-night-choral',
      },
    ],
  },
  {
    id: 5,
    playlistName: 'Best Of Moby',
    genre: ['electro', 'downtempo', 'ambient', 'techno'],
    description: 'One of the most important electronic dance music figures of the 90s. With more than 20 albums released, it wasn t easy to choose. This playlist deserves much more tracks!',
    totalTime: '',
    photo: require('./asset/moby-img.png'),
    youtube: 'https://www.youtube.com/watch?v=QhZnEagfjTQ&list=PLGcMNmVTewK-SxM3q1HtZFyJm29In7Xjq',
    musics: [
      {
        track: 1,
        artist: 'Moby',
        title: 'Porcelain',
        time: 4.06,
        link: 'https://www.youtube.com/watch?v=QhZnEagfjTQ',
      },
      {
        track: 2,
        artist: 'Moby',
        title: 'Mistake',
        time: 4.16,
        link: 'https://www.youtube.com/watch?v=LI-jUL07pXw',
      },
      {
        track: 3,
        artist: 'Moby',
        title: 'The Last Day',
        time: 3.44,
        link: 'https://www.youtube.com/watch?v=x5Dpz6w_jz4',
      },
      {
        track: 4,
        artist: 'Moby',
        title: 'In This World',
        time: 4.03,
        link: 'https://www.youtube.com/watch?v=6ci9eciX_cc',
      },
      {
        track: 5,
        artist: 'Moby',
        title: 'Sevastopol',
        time: 4.22,
        link: 'https://www.youtube.com/watch?v=0_7p9tGBA18',
      },
      {
        track: 6,
        artist: 'Moby',
        title: 'Signs Of Love',
        time: 4.28,
        link: 'https://www.youtube.com/watch?v=rNykVW_BuvM',
      },
      {
        track: 7,
        artist: 'Moby',
        title: 'One Of These Mornings',
        time: 3.15,
        link: 'https://www.youtube.com/watch?v=hqxbSggZ-vI',
      },
      {
        track: 8,
        artist: 'Moby',
        title: 'In My Heart',
        time: 4.39,
        link: 'https://www.youtube.com/watch?v=qp7KX1h3i_w',
      },
      {
        track: 9,
        artist: 'Moby',
        title: 'Sunday (The Day Before My Birthday)',
        time: 5.10,
        link: 'https://www.youtube.com/watch?v=AAB_YncprvI',
      },
      {
        track: 10,
        artist: 'Moby',
        title: 'Morningside',
        time: 5.31,
        link: 'https://www.youtube.com/watch?v=tpMijLl9Lfc',
      },
      {
        track: 11,
        artist: 'Moby',
        title: 'Natural Blues',
        time: 4.12,
        link: 'https://www.youtube.com/watch?v=JNWhOJSzZ0M',
      },
      {
        track: 12,
        artist: 'Moby',
        title: 'Why Does My Heart Feel So Bad',
        time: 3.51,
        link: 'https://www.youtube.com/watch?v=qT6XCvDUUsU',
      },
    ],
  },
  {
    id: 6,
    playlistName: 'IDM',
    genre: ['IDM', 'electro', 'ambient techno', 'breakbeat'],
    description: 'A palette of electronic and rave music styles. Regarded as better suited to home listening than dancing',
    totalTime: '',
    photo: require('./asset/idm-1-img.png'),
    youtube: 'https://www.youtube.com/watch?v=3BF_zuOYFn0&list=PLGcMNmVTewK81myPTTkJiPhWLd0bvksL-',
    musics: [
      {
        track: 1,
        artist: 'Rone feat. Gaspar Claus',
        title: 'Freaks',
        time: 4.54,
        link: 'https://www.youtube.com/watch?v=3BF_zuOYFn0',
      },
      {
        track: 2,
        artist: 'Squarepusher',
        title: 'Planetarium',
        time: 6.11,
        link: 'https://www.youtube.com/watch?v=5crdJgQcR3Q',
      },
      {
        track: 3,
        artist: 'Tycho',
        title: 'Dictaphones Lament',
        time: 5.11,
        link: 'https://www.youtube.com/watch?v=AXiZgRGSttk',
      },
      {
        track: 4,
        artist: 'Aphex Twin',
        title: 'Fork Rave',
        time: 4.08,
        link: 'https://www.youtube.com/watch?v=-QwpDJ_vDek',
      },
      {
        track: 5,
        artist: 'Ed Chamberlain',
        title: 'Styge',
        time: 6.13,
        link: 'https://www.youtube.com/watch?v=bamFxUpyP0M',
      },
      {
        track: 6,
        artist: 'Rykard',
        title: 'Out Of The Orchid Way',
        time: 5.40,
        link: 'https://www.youtube.com/watch?v=dFb5F6Vj7M0',
      },
      {
        track: 7,
        artist: 'Solar Fields',
        title: 'Inherit Velocity',
        time: 2.40,
        link: 'https://www.youtube.com/watch?v=FOOoU5MTdBM',
      },
      {
        track: 8,
        artist: 'Ochre',
        title: '111',
        time: 7.49,
        link: 'https://www.youtube.com/watch?v=qm1WmccaMhk',
      },
      {
        track: 9,
        artist: 'Lone',
        title: 'Memory Pool',
        time: 3.24,
        link: 'https://www.youtube.com/watch?v=5sAXyH1Jtzs',
      },
      {
        track: 10,
        artist: 'Boards Of Canada',
        title: 'Telephasic Workshop',
        time: 6.36,
        link: 'https://www.youtube.com/watch?v=soAH__YofsM',
      },
      {
        track: 11,
        artist: 'Plaid',
        title: 'Hawkmoth',
        time: 4.49,
        link: 'https://www.youtube.com/watch?v=AJ6I6J0yrHQ',
      },
      {
        track: 12,
        artist: 'Moderat',
        title: 'Milk',
        time: 10.06,
        link: 'https://www.youtube.com/watch?v=9PoPv0Gj9_o',
      },
    ],
  },
  {
    id: 7,
    playlistName: 'Best of Aphex Twin',
    genre: ['IDM', 'experimental', 'electro', 'acid techno'],
    description: 'A significant musician, composer and DJ, and one of the most influential artists in contemporary electronic music',
    totalTime: '',
    photo: require('./asset/aphex-twin-img.png'),
    youtube: 'https://www.youtube.com/watch?v=0Z4cLmbw6q0&list=PLGcMNmVTewK-woK5gmRhl3N_XUoreqN27',
    musics: [
      {
        track: 1,
        artist: 'Aphex twin',
        title: 'Heliosphan',
        time: 4.57,
        link: 'https://www.youtube.com/watch?v=0Z4cLmbw6q0',
      },
      {
        track: 2,
        artist: 'Aphex twin',
        title: 'Rhubarb',
        time: 7.45,
        link: 'https://www.youtube.com/watch?v=_AWIqXzvX-U',
      },
      {
        track: 3,
        artist: 'Aphex twin',
        title: 'Make A Baby',
        time: 2.28,
        link: 'https://www.youtube.com/watch?v=jcTejHJl2F0',
      },
      {
        track: 4,
        artist: 'Aphex twin',
        title: 'Didgeridoo',
        time: 7.12,
        link: 'https://www.youtube.com/watch?v=S5UBYOv1G9A',
      },
      {
        track: 5,
        artist: 'Aphex twin',
        title: 'IZ-US',
        time: 2.58,
        link: 'https://www.youtube.com/watch?v=dLHtV_S2HZw',
      },
      {
        track: 6,
        artist: 'Aphex twin',
        title: 'Crying In Your Face',
        time: 4.30,
        link: 'https://www.youtube.com/watch?v=AhMukHbUYJ0',
      },
      {
        track: 7,
        artist: 'Aphex twin',
        title: 'Pulsewidth',
        time: 3.49,
        link: 'https://www.youtube.com/watch?v=OtVp5fDBFM4',
      },
      {
        track: 8,
        artist: 'Aphex twin',
        title: 'Hedphelym',
        time: 6.04,
        link: 'https://www.youtube.com/watch?v=3RWWqJfwk1Q',
      },
      {
        track: 9,
        artist: 'Aphex twin',
        title: 'Ptolemy',
        time: 7.15,
        link: 'https://www.youtube.com/watch?v=hjOzJFyRE78',
      },
      {
        track: 10,
        artist: 'Aphex twin',
        title: 'Xtal',
        time: 4.55,
        link: 'https://www.youtube.com/watch?v=2tOutF8B3f8',
      },
      {
        track: 11,
        artist: 'Aphex twin',
        title: '34.5 P.e',
        time: 7.21,
        link: 'https://www.youtube.com/watch?v=r9EWrkExVrQ',
      },
      {
        track: 12,
        artist: 'Aphex twin',
        title: 'Laricheard',
        time: 2.18,
        link: 'https://www.youtube.com/watch?v=92Bhc4geWQ4',
      },
    ],
  },
  {
    id: 8,
    playlistName: 'Best Of Massive Attack',
    genre: ['trip hop', 'downtempo', 'electro'],
    description: 'One of the greatest, "trip-hop" group. Because Massive Attack music is so unique, they deserve their own playlist',
    totalTime: '',
    photo: require('./asset/massive-attack-img.png'),
    youtube: 'https://www.youtube.com/watch?v=Tb0MC0jFv6M&list=PLGcMNmVTewK8__Tpkceq8NOngUJNx1_lT',
    musics: [
      {
        track: 1,
        artist: 'Massive Attack',
        title: 'Teardrop',
        time: 5.31,
        link: 'https://www.youtube.com/watch?v=Tb0MC0jFv6M',
      },
      {
        track: 2,
        artist: 'Massive Attack feat. Hope Sandoval',
        title: 'The Spoils',
        time: 6.19,
        link: 'https://www.youtube.com/watch?v=8r31DFrFs5A',
      },
      {
        track: 3,
        artist: 'Massive Attack',
        title: 'Sly',
        time: 5.25,
        link: 'https://www.youtube.com/watch?v=LLV_-WDPYX4',
      },
      {
        track: 4,
        artist: 'Massive Attack',
        title: 'Silent Spring',
        time: 3.08,
        link: 'https://www.youtube.com/watch?v=1n8Xg3_YaqM',
      },
      {
        track: 5,
        artist: 'Massive Attack',
        title: 'Joy Luck Club',
        time: 4.59,
        link: 'https://www.youtube.com/watch?v=zOQ8dRPHgf4',
      },
      {
        track: 6,
        artist: 'Massive Attack',
        title: 'Atlas Air',
        time: 7.49,
        link: 'https://www.youtube.com/watch?v=C-9yxZHVJ_I',
      },
      {
        track: 7,
        artist: 'Massive Attack',
        title: 'Paradise Circus',
        time: 5.15,
        link: 'https://www.youtube.com/watch?v=jEgX64n3T7g',
      },
      {
        track: 8,
        artist: 'Massive Attack',
        title: 'Black Milk',
        time: 6.22,
        link: 'https://www.youtube.com/watch?v=Bf9AgX4Ixs4',
      },
      {
        track: 9,
        artist: 'Massive Attack',
        title: 'Exchange',
        time: 4.12,
        link: 'https://www.youtube.com/watch?v=wlc7cikBpg4',
      },
      {
        track: 10,
        artist: 'Massive Attack',
        title: 'Protection',
        time: 7.52,
        link: 'https://www.youtube.com/watch?v=h3-PvKIc3e4',
      },
      {
        track: 11,
        artist: 'Massive Attack',
        title: 'Unfinished Sympathy',
        time: 5.16,
        link: 'https://www.youtube.com/watch?v=oWohPJHicFE',
      },
    ],
  },
  {
    id: 9,
    playlistName: 'Ambient Chillout',
    genre: ['ambient', 'psybient', 'etchno-chillout', 'psychill'],
    description: 'The sun of psychedelic downtempo music which brings light in multiple colours and shapes',
    totalTime: '',
    photo: require('./asset/chillout-img.png'),
    youtube: 'https://www.youtube.com/watch?v=p1oGMZKEzZs&list=PLGcMNmVTewK-SMJNgIrpERUBMBHoLMam9',
    musics: [
      {
        track: 1,
        artist: 'Argus',
        title: 'We Are One (Suduaya Remix)',
        time: 5.41,
        link: 'https://www.youtube.com/watch?v=EgzMKjBY-nM',
      },
      {
        track: 2,
        artist: 'Solar Fields',
        title: 'Sky Trees',
        time: 7.06,
        link: 'https://www.youtube.com/watch?v=rPxmS3HuEms',
      },
      {
        track: 3,
        artist: 'Aeon Waves',
        title: 'Voices',
        time: 5.55,
        link: 'https://www.youtube.com/watch?v=song9JYlmxo',
      },
      {
        track: 4,
        artist: 'Solar Fields',
        title: 'A New Window',
        time: 9.36,
        link: 'https://www.youtube.com/watch?v=C-k-hTXlAWA',
      },
      {
        track: 5,
        artist: 'Carbon Based Lifeform',
        title: 'Derelicts',
        time: 6.13,
        link: 'https://www.youtube.com/watch?v=Usm21SfV-p8',
      },
      {
        track: 6,
        artist: 'Lauge & Baba Gnohm',
        title: 'Hypnose',
        time: 8.02,
        link: 'https://www.youtube.com/watch?v=g9w5hDYQ720',
      },
      {
        track: 7,
        artist: 'Asura',
        title: 'Eternal Sunshine (Ambient Mix)',
        time: 6.55,
        link: 'https://www.youtube.com/watch?v=KnQWe1DYPb8',
      },
      {
        track: 8,
        artist: 'Reasonandu & Adrian Enescu',
        title: 'Peaceful Heart',
        time: 6.11,
        link: 'https://www.youtube.com/watch?v=qgbLTYz5E6k',
      },
      {
        track: 9,
        artist: 'Solar Fields',
        title: 'Our Blue Stones',
        time: 6.44,
        link: 'https://www.youtube.com/watch?v=S4-eFoSp71k',
      },
      {
        track: 10,
        artist: 'Lauge & Baba Gnohm feat. Vonoom',
        title: 'Through Endless Ice Waters',
        time: 6.35,
        link: 'https://www.youtube.com/watch?v=b8ylB2y5ISg',
      },
      {
        track: 11,
        artist: 'Aes Dana',
        title: 'Opalin',
        time: 7.15,
        link: 'https://www.youtube.com/watch?v=p1oGMZKEzZs',
      },
      {
        track: 12,
        artist: 'Logical Element',
        title: 'Falling',
        time: 11.14,
        link: 'https://www.youtube.com/watch?v=PB-Y7jEoJ2E',
      },
    ],
  },
  {
    id: 10,
    playlistName: 'Lounge Cafe',
    genre: ['lounge', 'ambient', 'chillout'],
    description: 'Musics that emphasizing a chilled-out atmosphere with light instrumentation and sometimes vocals indebted to vocal jazz',
    totalTime: '',
    photo: require('./asset/lounge-cafe-img.png'),
    youtube: 'https://www.youtube.com/watch?v=t11W2nnYj7A&list=PLGcMNmVTewK9lmfLmmqAeegoYBIwQPx3n',
    musics: [
      {
        track: 1,
        artist: 'Five Seasons',
        title: 'Something In The Air',
        time: 4.51,
        link: 'https://www.youtube.com/watch?v=t11W2nnYj7A',
      },
      {
        track: 2,
        artist: 'Eric Hilton',
        title: 'Continuum',
        time: 3.41,
        link: 'https://www.youtube.com/watch?v=S9sqyCpBJ_k',
      },
      {
        track: 3,
        artist: 'Thievery Corporation feat. Herb Alpert',
        title: 'Lemon Tree',
        time: 3.38,
        link: 'https://www.youtube.com/watch?v=l_0K7yvCW_w',
      },
      {
        track: 4,
        artist: 'Chris Coco',
        title: 'Summer Sun',
        time: 3.52,
        link: 'https://www.youtube.com/watch?v=dj0RyqCU1pc',
      },
      {
        track: 5,
        artist: 'Air',
        title: 'Modular Mix',
        time: 5.45,
        link: 'https://www.youtube.com/watch?v=JX1EfZnJcHE',
      },
      {
        track: 6,
        artist: 'Mindseye',
        title: 'Summer Breeze',
        time: 3.26,
        link: 'https://www.youtube.com/watch?v=Yiis_mioR5U',
      },
      {
        track: 7,
        artist: 'Jens Buchert',
        title: 'Lichtwesen',
        time: 4.48,
        link: 'https://www.youtube.com/watch?v=Oxb8nF3VBzQ',
      },
      {
        track: 8,
        artist: 'AIM',
        title: 'Cold Water Music',
        time: 5.45,
        link: 'https://www.youtube.com/watch?v=ll1SzT0VdZE',
      },
      {
        track: 9,
        artist: 'Der Waldlaufer',
        title: 'Water Moon',
        time: 5.28,
        link: 'https://www.youtube.com/watch?v=JPVOYJA5A_s',
      },
      {
        track: 10,
        artist: 'Five Seasons',
        title: 'Love Apple (Lemongrass Wet Dreams Remix)',
        time: 3.51,
        link: 'https://www.youtube.com/watch?v=jllaQlpsdl0',
      },
      {
        track: 11,
        artist: 'Shapeshifter',
        title: 'Summer Haze',
        time: 6.44,
        link: 'https://www.youtube.com/watch?v=oNtB2JFVN2c',
      },
      {
        track: 12,
        artist: 'Nightmares On Wax',
        title: 'Les Nuits',
        time: 6.14,
        link: 'https://www.youtube.com/watch?v=YysyzCW25ig',
      },
    ],
  },
  {
    id: 11,
    playlistName: 'Best Of Eitan Reiter',
    genre: [
      'electro',
      'psybient',
      'progressive house',
      'deep house',
      'techno',
    ],
    description: 'Israeli musician and producer, he performed in many electronic and psytrance fesivals around the globe',
    totalTime: '',
    photo: require('./asset/eitan-reiter-img.png'),
    youtube: '',
    musics: [
      {
        track: 1,
        artist: 'Eitan Reiter & A Balter',
        title: 'Happy Fat Kids',
        time: 7.06,
        link: 'https://www.youtube.com/watch?v=HVRaB9oI58E',
      },
      {
        track: 2,
        artist: 'Eitan Reiter',
        title: 'Pyramid',
        time: 8.20,
        link: 'https://www.youtube.com/watch?v=qI6wEhtsqio',
      },
      {
        track: 3,
        artist: 'Eitan Reiter',
        title: 'Choices',
        time: 8.11,
        link: 'https://www.youtube.com/watch?v=EyI4PzCwdLY',
      },
      {
        track: 4,
        artist: 'Perfect Stranger',
        title: 'Stardust (Eitan Reiter Remix)',
        time: 9.32,
        link: 'https://www.youtube.com/watch?v=tpBTXN3LGXc',
      },
      {
        track: 5,
        artist: 'Eitan Reiter',
        title: 'The 1st (X Dream Remix)',
        time: 10.12,
        link: 'https://www.youtube.com/watch?v=7WXZ6_1CIg4',
      },
      {
        track: 6,
        artist: 'Eitan Reiter',
        title: 'Ups And Downs (Perfect Stranger Re Edit)',
        time: 11.16,
        link: 'https://www.youtube.com/watch?v=O4PhAvIJwXI',
      },
      {
        track: 7,
        artist: 'Eitan Reiter',
        title: 'Eat You',
        time: 10.25,
        link: 'https://www.youtube.com/watch?v=gqGId6P9nwQ',
      },
      {
        track: 8,
        artist: 'Eitan Reiter',
        title: 'First Steps Outdoor Sessions #3 / Give If Life',
        time: 8.06,
        link: 'https://www.youtube.com/watch?v=fL1NH-kK9sA',
      },
      {
        track: 9,
        artist: 'Eitan Reiter',
        title: 'Just Another Night Part 2',
        time: 4.09,
        link: 'https://www.youtube.com/watch?v=XCx0PfWCKoU',
      },
      {
        track: 10,
        artist: 'A Batler',
        title: 'You re A Fish - Boom Festival 2016 (Eitan Reiter Remix)',
        time: 10.01,
        link: 'https://www.youtube.com/watch?v=VWOoRzI1tjc',
      },
      {
        track: 11,
        artist: 'Eitan Reiter',
        title: 'Midnight Glide',
        time: 7.37,
        link: 'https://www.youtube.com/watch?v=kKbEMvk4TVI',
      },
      {
        track: 12,
        artist: 'Eitan Reiter & Audio Junkies',
        title: 'How Low - Boom Festival Edition',
        time: 6.01,
        link: 'https://www.youtube.com/watch?v=eavBYjGucOg',
      },
    ],
  },
  {
    id: 12,
    playlistName: 'Relax',
    genre: ['ambient', 'atmospheric', 'space ambient'],
    description: 'Take a deep breath - This playlist can work well for sleep, meditation, focus, relaxation, work, reading, spa, studying and more',
    totalTime: '',
    photo: require('./asset/relax-img.png'),
    youtube: '',
    musics: [
      {
        track: 1,
        artist: 'Feel',
        title: 'Der Waldlaufer',
        time: 5.09,
        link: 'https://www.youtube.com/watch?v=nhph3dNNGgU',
      },
      {
        track: 2,
        artist: 'Moby',
        title: 'Memory Gospel',
        time: 6.44,
        link: 'https://www.youtube.com/watch?v=sSY5HaXxTgI',
      },
      {
        track: 3,
        artist: 'Boards Of Canada',
        title: 'Amo Bishop Roden',
        time: 6.17,
        link: 'https://www.youtube.com/watch?v=KZbFpcEl-8o',
      },
      {
        track: 4,
        artist: 'Hiatus',
        title: 'Becoming',
        time: 3.16,
        link: 'https://www.youtube.com/watch?v=F8Y2PFFCfJk',
      },
      {
        track: 5,
        artist: 'Stellardrone',
        title: 'Eternity',
        time: 6.22,
        link: 'https://www.youtube.com/watch?v=m-0H4HOATOM',
      },
      {
        track: 6,
        artist: 'Global Communication',
        title: 'Epsilon Phase',
        time: 11.00,
        link: 'https://www.youtube.com/watch?v=M5tm3Oe4pYg',
      },
      {
        track: 7,
        artist: 'EL LCD',
        title: 'Snö på Hisingen (Carbon Based Lifeform Remix)',
        time: 6.25,
        link: 'https://www.youtube.com/watch?v=-QlrNzBcNyY',
      },
      {
        track: 8,
        artist: 'Der Waldlaufer & Lauge',
        title: 'Morgenfrisk',
        time: 3.12,
        link: 'https://www.youtube.com/watch?v=5PM8sXA-ryE',
      },
      {
        track: 9,
        artist: 'Der Waldlaufer',
        title: 'En Route',
        time: 5.22,
        link: 'https://www.youtube.com/watch?v=h53vbbI-bWA',
      },
      {
        track: 10,
        artist: 'Moby',
        title: 'JLTF 1',
        time: 4.41,
        link: 'https://www.youtube.com/watch?v=W1RKbt-gacY',
      },
      {
        track: 11,
        artist: 'Roger Neill',
        title: 'Santa Barbara, 1979',
        time: 2.37,
        link: 'https://www.youtube.com/watch?v=lblJCPycN4A',
      },
      {
        track: 12,
        artist: 'Icefield',
        title: 'Starlight',
        time: 3.51,
        link: 'https://www.youtube.com/watch?v=MbAOZfLPucI',
      },
    ],
  },
  {
    id: 13,
    playlistName: 'Best Of Solar Fields',
    genre: ['electro', 'ambient', 'psybient', 'progressive trance'],
    description: 'In the late 90s, Swedish composer Magnus Birgersson created Solar Fields, a project considered like one of the most productive and creative in the Scandinavian electronic music scene',
    totalTime: '',
    photo: require('./asset/solar-fields-img.png'),
    youtube: '',
    musics: [
      {
        track: 1,
        artist: 'Solar Fields',
        title: 'Sol',
        time: 8.24,
        link: 'https://www.youtube.com/watch?v=9KKN5ZJlubQ',
      },
      {
        track: 2,
        artist: 'Solar Fields',
        title: 'Times Are Good (Sometimes Remix)',
        time: 8.10,
        link: 'https://www.youtube.com/watch?v=ptgQqC8m4xE',
      },
      {
        track: 3,
        artist: 'Solar Fields',
        title: 'Unite',
        time: 9.24,
        link: 'https://www.youtube.com/watch?v=JDqjkIVgcr8',
      },
      {
        track: 4,
        artist: 'Solar Fields',
        title: 'Insum (2019 Remaster)',
        time: 8.24,
        link: 'https://www.youtube.com/watch?v=njYw6U8SfFo',
      },
      {
        track: 5,
        artist: 'Solar Fields',
        title: 'The Stones Are Not Too Busy (2018 Remaster)',
        time: 10.31,
        link: 'https://www.youtube.com/watch?v=bvaL_ohykUg',
      },
      {
        track: 6,
        artist: 'Solar Fields',
        title: 'Kick Back',
        time: 8.52,
        link: 'https://www.youtube.com/watch?v=FGz2WnhEh-8',
      },
      {
        track: 7,
        artist: 'Solar Fields',
        title: 'Swoosh',
        time: 8.35,
        link: 'https://www.youtube.com/watch?v=wLmrm8O5CLU',
      },
      {
        track: 8,
        artist: 'Solar Fields',
        title: 'Video 2007',
        time: 8.22,
        link: 'https://www.youtube.com/watch?v=4HFikRXdt8I',
      },
      {
        track: 9,
        artist: 'Solar Fields',
        title: 'We Are The Dream',
        time: 8.12,
        link: 'https://www.youtube.com/watch?v=LkUr-YFmfL8',
      },
      {
        track: 10,
        artist: 'Solar Fields',
        title: 'Confusion Illusion (Remix)',
        time: 7.20,
        link: 'https://www.youtube.com/watch?v=mPb3OKHfCdI',
      },
      {
        track: 11,
        artist: 'Solar Fields',
        title: 'Cocoon moon (Glastonbury Festival 2005 Mix)',
        time: 10.37,
        link: 'https://www.youtube.com/watch?v=BndzTjviflE',
      },
    ],
  },
  {
    id: 14,
    playlistName: 'Best Of Ott',
    genre: ['dub', 'electro', 'trip hop', 'ethnic electro', 'ambient'],
    description: 'Ott is a British record producer and musician who has worked with Sinéad O Connor, Embrace, the Orb, and Brian Eno, and has achieved recognition since 2002 for his own psychedelic dub tracks and his collaborations',
    totalTime: '',
    photo: require('./asset/ott-img.png'),
    youtube: 'https://www.youtube.com/watch?v=xUtlrbOkxN0&list=PLGcMNmVTewK9RhzMtBeEkj3tZqL0__cP3',
    musics: [
      {
        track: 1,
        artist: 'OTT',
        title: 'Signals From Bob',
        time: 7.48,
        link: 'https://www.youtube.com/watch?v=xUtlrbOkxN0',
      },
      {
        track: 2,
        artist: 'OTT',
        title: 'Joyful Wonder',
        time: 6.38,
        link: 'https://www.youtube.com/watch?v=MExx00lnlh0',
      },
      {
        track: 3,
        artist: 'OTT',
        title: 'The Queen Of All Everything',
        time: 7.53,
        link: 'https://www.youtube.com/watch?v=116gLvsQA4A',
      },
      {
        track: 4,
        artist: 'OTT',
        title: 'A Happening In Your Head',
        time: 7.10,
        link: 'https://www.youtube.com/watch?v=fMwS9Ip8c-E',
      },
      {
        track: 5,
        artist: 'OTT',
        title: 'Squirrel And Biscuits',
        time: 6.03,
        link: 'https://www.youtube.com/watch?v=6vszOgNRvWI',
      },
      {
        track: 6,
        artist: 'OTT',
        title: 'Unit Delta Plus',
        time: 8.11,
        link: 'https://www.youtube.com/watch?v=aSxiNnWbJOE',
      },
      {
        track: 7,
        artist: 'OTT',
        title: 'Splitting An Atom',
        time: 7.22,
        link: 'https://www.youtube.com/watch?v=YX5SJtZ5xPE',
      },
      {
        track: 8,
        artist: 'OTT',
        title: 'Owl Stretching Time',
        time: 7.42,
        link: 'https://www.youtube.com/watch?v=PaJiZX7BYN0',
      },
      {
        track: 9,
        artist: 'OTT',
        title: 'Harwell Dekatron',
        time: 6.54,
        link: 'https://www.youtube.com/watch?v=Sydc8et9RMs',
      },
      {
        track: 10,
        artist: 'OTT',
        title: 'Mouse Eating Cheese',
        time: 7.39,
        link: 'https://www.youtube.com/watch?v=DmqK1EKcvCs',
      },
      {
        track: 11,
        artist: 'OTT',
        title: 'Rogue Bagel',
        time: 8.30,
        link: 'https://www.youtube.com/watch?v=OnLhzs7d0E8',
      },
    ],
  },
  {
    id: 15,
    playlistName: 'Best of Rone',
    genre: ['electro', 'EDM', 'IDM', 'minimal techno'],
    description:
      'Rone (born Erwan Castex) is a French electro music producer and artist',
    totalTime: '',
    photo: require('./asset/rone-img.png'),
    youtube: 'https://www.youtube.com/watch?v=GZc8kB6OfXs&list=PLGcMNmVTewK9QyZDOBMwom8ds4ueINS3_',
    musics: [
      {
        track: 1,
        artist: 'Rone',
        title: '(OO)',
        time: 2.56,
        link: 'https://www.youtube.com/watch?v=GZc8kB6OfXs',
      },
      {
        track: 2,
        artist: 'Rone',
        title: 'Spanish Breakfast',
        time: 3.37,
        link: 'https://www.youtube.com/watch?v=31Yc1v4Wj_k',
      },
      {
        track: 3,
        artist: 'Rone',
        title: 'Parade',
        time: 3.28,
        link: 'https://www.youtube.com/watch?v=GW7iHpkUGLU',
      },
      {
        track: 4,
        artist: 'Rone',
        title: 'Beast',
        time: 7.15,
        link: 'https://www.youtube.com/watch?v=Vb8jhPCDKUk',
      },
      {
        track: 5,
        artist: 'Rone',
        title: 'Fugu Kiss',
        time: 4.47,
        link: 'https://www.youtube.com/watch?v=_9_D0vcIqHg',
      },
      {
        track: 6,
        artist: 'Rone',
        title: 'Gravity',
        time: 3.52,
        link: 'https://www.youtube.com/watch?v=7ZxqhHhHFxI',
      },
      {
        track: 7,
        artist: 'Rone',
        title: 'Memory',
        time: 5.19,
        link: 'https://www.youtube.com/watch?v=CCZleg3yQaE',
      },
      {
        track: 8,
        artist: 'Rone',
        title: 'Sing Song',
        time: 4.00,
        link: 'https://www.youtube.com/watch?v=ZiHaMnlkGx8',
      },
      {
        track: 9,
        artist: 'Rone',
        title: 'Spank',
        time: 4.05,
        link: 'https://www.youtube.com/watch?v=p2nlFcShUCs',
      },
      {
        track: 10,
        artist: 'Rone',
        title: 'Bora Vocal',
        time: 5.37,
        link: 'https://www.youtube.com/watch?v=Dzrw52pTpso',
      },
      {
        track: 11,
        artist: 'Rone',
        title: 'La Grande Ourse',
        time: 3.41,
        link: 'https://www.youtube.com/watch?v=s8Q9Fz09XVM',
      },
      {
        track: 12,
        artist: 'Rone',
        title: 'Beast Part 2',
        time: 6.26,
        link: 'https://www.youtube.com/watch?v=cVU34JKJR1o',
      },
    ],
  },
  {
    id: 16,
    playlistName: 'Best Of Koan',
    genre: [
      'minimal techno',
      'breakbeat',
      'progressive house',
      'etchno-chillout',
      'downtempo',
      'electro house',
    ],
    description: 'A Russian duo consisting of Danial Roeth and William Grey',
    totalTime: '',
    photo: require('./asset/koan-img.png'),
    youtube: 'https://www.youtube.com/watch?v=jo4m-FYxBpA&list=PLGcMNmVTewK_nYPovV30BnZyrvTleEhkC',
    musics: [
      {
        track: 1,
        artist: 'Koan',
        title: 'Conscious Delusion',
        time: 7.37,
        link: 'https://www.youtube.com/watch?v=7wH7TyIVyQM',
      },
      {
        track: 2,
        artist: 'Koan',
        title: 'Uncloak',
        time: 10.37,
        link: 'https://www.youtube.com/watch?v=RAy5xgKpbS0',
      },
      {
        track: 3,
        artist: 'Koan',
        title: 'Titania (Crying Heavens Mix)',
        time: 8.11,
        link: 'https://www.youtube.com/watch?v=0tXzJY7rlR8',
      },
      {
        track: 4,
        artist: 'Koan',
        title: 'Penance (Condemned Mix)',
        time: 5.48,
        link: 'https://www.youtube.com/watch?v=eS46T8m1qUc',
      },
      {
        track: 5,
        artist: 'Koan',
        title: 'She Doesnt Know To Be Asleep',
        time: 8.21,
        link: 'https://www.youtube.com/watch?v=kpP7B23-KF8',
      },
      {
        track: 6,
        artist: 'Koan',
        title: 'Agartha',
        time: 8.53,
        link: 'https://www.youtube.com/watch?v=eN4QMfbow28',
      },
      {
        track: 7,
        artist: 'Koan',
        title: 'The Light Of Sleeping Star (Serenity Mix)',
        time: 8.25,
        link: 'https://www.youtube.com/watch?v=R5eAjFTmjnI',
      },
      {
        track: 8,
        artist: 'Koan',
        title: 'Immersion',
        time: 8.52,
        link: 'https://www.youtube.com/watch?v=WGiCz_1-NoE',
      },
      {
        track: 9,
        artist: 'Koan',
        title: 'Cold Paints',
        time: 7.28,
        link: 'https://www.youtube.com/watch?v=QO5SmdVket0',
      },
      {
        track: 10,
        artist: 'Koan',
        title: 'Fairyland (Eddur Mix)',
        time: 8.57,
        link: 'https://www.youtube.com/watch?v=OhrjgEjdxs0',
      },
      {
        track: 11,
        artist: 'Koan',
        title: 'Awakening (Remix)',
        time: 9.21,
        link: 'https://www.youtube.com/watch?v=UtwiucwGu8c',
      },
      {
        track: 12,
        artist: 'Koan',
        title: 'Introus',
        time: 2.11,
        link: 'https://www.youtube.com/watch?v=jo4m-FYxBpA',
      },
    ],
  },
  {
    id: 17,
    playlistName: 'Best Of Eric Hilton',
    genre: ['lounge', 'chillout', 'downtempo', 'electro', 'trip hop'],
    description: 'Eric Hilton is an artist/producer who uses old-school skills to craft new school chill',
    totalTime: '',
    photo: require('./asset/eric-hilton-img.png'),
    youtube: '',
    musics: [
      {
        track: 1,
        artist: 'Eric Hilton',
        title: 'Forming Star',
        time: 4.55,
        link: 'https://www.youtube.com/watch?v=3dcfdKsYXu4',
      },
      {
        track: 2,
        artist: 'Eric Hilton',
        title: 'Expert Dreaming',
        time: 3.41,
        link: 'https://www.youtube.com/watch?v=CUy_zB94X-s',
      },
      {
        track: 3,
        artist: 'Eric Hilton',
        title: 'The Grand Beauty',
        time: 3.45,
        link: 'https://www.youtube.com/watch?v=QoJxyTpgMwA',
      },
      {
        track: 4,
        artist: 'Eric Hilton',
        title: 'More Beautiful Things',
        time: 3.53,
        link: 'https://www.youtube.com/watch?v=ao35fOgNPJA',
      },
      {
        track: 5,
        artist: 'Eric Hilton',
        title: 'Fade Into Forever',
        time: 5.25,
        link: 'https://www.youtube.com/watch?v=tcRAPAzhvXc',
      },
      {
        track: 6,
        artist: 'Eric Hilton',
        title: 'Artifact22',
        time: 4.31,
        link: 'https://www.youtube.com/watch?v=eVqOfsKqIeo',
      },
      {
        track: 7,
        artist: 'Eric Hilton',
        title: 'Ceremony',
        time: 5.21,
        link: 'https://www.youtube.com/watch?v=mEk5DcUMJxE',
      },
      {
        track: 8,
        artist: 'Eric Hilton',
        title: 'Particles',
        time: 4.21,
        link: 'https://www.youtube.com/watch?v=PXE3J2Jc2l0',
      },
      {
        track: 9,
        artist: 'Eric Hilton',
        title: 'Tomorrows Shadow',
        time: 3.42,
        link: 'https://www.youtube.com/watch?v=tcWKkxevz5A',
      },
      {
        track: 10,
        artist: 'Eric Hilton',
        title: 'Strata 1',
        time: 3.54,
        link: 'https://www.youtube.com/watch?v=6ZukKy-5MkY',
      },
      {
        track: 11,
        artist: 'Eric Hilton',
        title: 'Infinite Everywhere',
        time: 3.23,
        link: 'https://www.youtube.com/watch?v=sm8yBJWzYNE',
      },
      {
        track: 12,
        artist: 'Eric Hilton',
        title: 'Lost Dialect',
        time: 3.28,
        link: 'https://www.youtube.com/watch?v=mSz3exdmkVU',
      },
    ],
  },
  // {
  //   id: 18,
  //   playlistName: 'Soundtrack',
  //   genre: [],
  //   description: '',
  //   totalTime: '',
  //   photo: require('./asset/soundtrack-img.png'),
  //   youtube: '',
  //   musics: [
  //     {
  //       track: 1,
  //       artist: 'Trent Reznor & Atticus Ross',
  //       title: 'Life On Mars? (David Bowie reprise) (Watchmen Soundtrack)',
  //       time: 2.54,
  //     },
  //     {
  //       track: 2,
  //       artist: 'Ramin Djawadi',
  //       title: 'Dr. Ford (Westworld Soundtrack)',
  //       time: 5.3,
  //     },
  //     {
  //       track: 3,
  //       artist: 'Air',
  //       title: 'Highschool Lover (Virgin Suicide Soundtrack)',
  //       time: 2.42,
  //     },
  //     {
  //       track: 4,
  //       artist: '',
  //       title: '(Kill Bill Soundtrack)',
  //       time: '',
  //     },
  //     {
  //       track: 5,
  //       artist: 'Brian Eno',
  //       title: 'Deep Blue Day (Trainspotting Soundtrack)',
  //       time: 3.59,
  //     },
  //     {
  //       track: 6,
  //       artist: 'Nathan Barr',
  //       title: 'Tripping (True Blood Soundtrack)',
  //       time: '',
  //     },
  //     {
  //       track: 7,
  //       artist: 'Vangelis',
  //       title: 'La Petite Fille De La Mer (Remastered) (Million Soundtrack)',
  //       time: 5.55,
  //     },
  //     {
  //       track: 8,
  //       artist: 'Squarepusher',
  //       title: 'Tommib (Lost In Translation Soundtrack)',
  //       time: 1.2,
  //     },
  //     {
  //       track: 9,
  //       artist: 'Moby',
  //       title: 'Extreme Ways (Jason Bourne Soundtrack)',
  //       time: '4.58',
  //       link: 'https://www.youtube.com/watch?v=ftm1hiXgYsA',
  //     },
  //     {
  //       track: 10,
  //       artist: 'Norah Jones',
  //       title: 'Black (Breaking Bad Soundtrack)',
  //       time: 3.32,
  //     },
  //     {
  //       track: 11,
  //       artist: 'Trent Reznor & Atticus Ross',
  //       title: 'Like Home (Gone Girl Soundtrack)',
  //       time: 3.4,
  //     },
  //   ],
  // },
  {
    id: 19,
    playlistName: 'IDM 2',
    genre: ['IDM', 'electro', 'ambient techno', 'breakbeat'],
    description: 'Some of the best Intelligent Dance Music tracks - II',
    totalTime: '',
    photo: require('./asset/idm-2-img.png'),
    youtube: 'https://www.youtube.com/watch?v=X_k2lih0T6U&list=PLGcMNmVTewK-9SdRTd4osgRp8LpTHDuLn',
    musics: [
      {
        track: 1,
        artist: 'Squarepusher',
        title: 'Midi Sans Frontières',
        time: 6.01,
        link: 'https://www.youtube.com/watch?v=X_k2lih0T6U',
      },
      {
        track: 2,
        artist: 'Am-Boy',
        title: 'A Place Of No Eyes',
        time: 3.36,
        link: 'https://www.youtube.com/watch?v=VWEDuQqn-Cg',
      },
      {
        track: 3,
        artist: 'James Holden',
        title: 'Blackpool Late Eighties',
        time: 8.39,
        link: 'https://www.youtube.com/watch?v=4ynDTwucfhY',
      },
      {
        track: 4,
        artist: 'Luke Abbot',
        title: 'Trans Forest Alignment',
        time: 5.01,
        link: 'https://www.youtube.com/watch?v=8cYhHQFjvZk',
      },
      {
        track: 5,
        artist: 'Jon Hopkins',
        title: 'Collider',
        time: 9.22,
        link: 'https://www.youtube.com/watch?v=S2CXrvcsbMk',
      },
      {
        track: 6,
        artist: 'Tor',
        title: 'Cymbol',
        time: 5.38,
        link: 'https://www.youtube.com/watch?v=Wysv6_IKw10',
      },
      {
        track: 7,
        artist: 'Rykard',
        title: 'The Transmission Fields',
        time: 3.03,
        link: 'https://www.youtube.com/watch?v=ISrlQ2GyoO0',
      },
      {
        track: 8,
        artist: 'Ed Chamberlain',
        title: 'Landmine',
        time: 7.20,
        link: 'https://www.youtube.com/watch?v=Gd3QYfTV4IE',
      },
      {
        track: 9,
        artist: 'Mindseye',
        title: 'Hang Ten (The Ocean)',
        time: 3.20,
        link: 'https://www.youtube.com/watch?v=IYfUX0pA45k',
      },
      {
        track: 10,
        artist: 'Nosaj Thing',
        title: 'Fog',
        time: 3.43,
        link: 'https://www.youtube.com/watch?v=SGcHPwQGkYg',
      },
      {
        track: 11,
        artist: 'Lone',
        title: 'Sea Of Tranquility',
        time: 5.00,
        link: 'https://www.youtube.com/watch?v=zd4mlmqvKzE',
      },
      {
        track: 12,
        artist: 'Burial',
        title: 'Southern Comfort',
        time: 5.02,
        link: 'https://www.youtube.com/watch?v=CGnUJ4wTLN4',
      },
    ],
  },
  {
    id: 20,
    playlistName: 'Best Of Carbon Based Lifeforms',
    genre: ['ambient', 'psybient', 'chillout'],
    description: 'Swedish electronic music duo formed by Johannes Hedberg and Daniel Vadestrid',
    totalTime: '',
    photo: require('./asset/carbon-based-lifeforms-img.png'),
    youtube: 'https://www.youtube.com/watch?v=ORro19RHIt0&list=PLGcMNmVTewK9JPG3lmqSKT4Y7Xv_6kMzn',
    musics: [
      {
        track: 1,
        artist: 'Carbon Based Lifeforms',
        title: 'Vision (Revisited)',
        time: 3.29,
        link: 'https://www.youtube.com/watch?v=TfipkU6N9PY',
      },
      {
        track: 2,
        artist: 'Carbon Based Lifeforms',
        title: 'Endospore (Remastered)',
        time: 5.04,
        link: 'https://www.youtube.com/watch?v=EK-1zW4ya0A',
      },
      {
        track: 3,
        artist: 'Carbon Based Lifeforms',
        title: 'Photosynthesis',
        time: 6.49,
        link: 'https://www.youtube.com/watch?v=bI1aZM8oh7o',
      },
      {
        track: 4,
        artist: 'Carbon Based Lifeforms',
        title: 'Supersede (First Version)',
        time: 9.25,
        link: 'https://www.youtube.com/watch?v=V4U7E6cMmx4',
      },
      {
        track: 5,
        artist: 'Carbon Based Lifeforms',
        title: 'T-Rex Echoes (Live)',
        time: 7.10,
        link: 'https://www.youtube.com/watch?v=w6O5LmdYtSg',
      },
      {
        track: 6,
        artist: 'Carbon Based Lifeforms',
        title: 'Proton / Electron',
        time: 6.52,
        link: 'https://www.youtube.com/watch?v=zec0qqohR0w',
      },
      {
        track: 7,
        artist: 'Carbon Based Lifeforms',
        title: 'Birdie',
        time: 5.37,
        link: 'https://www.youtube.com/watch?v=RRkiRL1cFb8',
      },
      {
        track: 8,
        artist: 'Carbon Based Lifeforms',
        title: 'Euphotic (Live)',
        time: 7.36,
        link: 'https://www.youtube.com/watch?v=Q8WcWBDeJks',
      },
      {
        track: 9,
        artist: 'Carbon Based Lifeforms',
        title: 'Leaves',
        time: 6.35,
        link: 'https://www.youtube.com/watch?v=mUHFFbm1Hto',
      },
      {
        track: 10,
        artist: 'Carbon Based Lifeforms',
        title: 'Flytta Dig',
        time: 6.25,
        link: 'https://www.youtube.com/watch?v=asRykF3l01c',
      },
      {
        track: 11,
        artist: 'Carbon Based Lifeforms',
        title: 'Lost',
        time: 5.22,
        link: 'https://www.youtube.com/watch?v=9FSCXeCApn4',
      },
      {
        track: 12,
        artist: 'Carbon Based Lifeforms',
        title: 'World Of Sleepers',
        time: 5.21,
        link: 'https://www.youtube.com/watch?v=ORro19RHIt0',
      },
    ],
  },
];

export default playlistData;
